SELECT
SUM(c2) OVER(ROWS BETWEEN 3 PRECEDING AND 1 FOLLOWING) as summation1,
SUM(c3) OVER(ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as summation4,
SUM(c4) OVER(PARTITION BY c6 ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as summation12,
SUM(c3) OVER(PARTITION BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) as summation13,
SUM(c3) OVER(PARTITION BY c1 ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as summation16,
SUM(c3) OVER(PARTITION BY c1,c3 ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as summation18,
CORR(c2, c3) OVER(ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as corr4,
CORR(c2, c3) OVER(ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) as corr5,
CORR(c2, c5) OVER(PARTITION BY c1 ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as corr8,
CORR(c4, c5) OVER(PARTITION BY c1 ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) as corr9,
CORR(c4, c11) OVER(PARTITION BY c3 ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as corr12,
CORR(c8, c11) OVER(PARTITION BY c7 ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) as corr13
FROM test;
